#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Add receptionist translations to django.po files."""
import os, polib

BASE = r'C:\Users\user\Desktop\healty-life-2'

strings = [
    "Panel de Recepción",
    "Dashboard",
    "Citas",
    "Facturación",
    "Pacientes",
    "Cerrar sesión",
    "Citas hoy",
    "Programadas",
    "Citas pendientes",
    "Por confirmar",
    "Pacientes nuevos hoy",
    "Registrados",
    "Médicos activos",
    "En turno",
    "Buscar paciente, médico o especialidad...",
    "Registrar paciente",
    "Gestión de Citas",
    "Inicio",
    "Gestionar",
    "Administra todas las citas del sistema",
    "Total citas",
    "Solicitudes",
    "Pagos por confirmar",
    "Aceptadas",
    "Buscar paciente, médico o especialidad...",
    "Limpiar filtros",
    "Todos los estados",
    "Solicitada",
    "Aprobada",
    "Pago Pendiente",
    "Pagada (Adelanto)",
    "Confirmada",
    "En Consulta",
    "Atendida",
    "Cancelada",
    "Rechazada",
    "No Asistió",
    "Todas las citas",
    "Solicitudes nuevas",
    "citas en total",
    "solicitudes pendientes",
    "en revisión",
    "aceptadas",
    "Sede",
    "Médico",
    "Acciones",
    "Método Pago",
    "Referencia",
    "Monto",
    "Fecha Cita",
    "Ver pago",
    "Confirmar",
    "Rechazar",
    "Confirmar Pago",
    "Cancelar",
    "Sin acciones",
    "No hay citas registradas.",
    "No hay solicitudes nuevas.",
    "No hay pagos pendientes de confirmación.",
    "Pago pendiente",
    "No asignado",
    "No registrado",
    "Confirmar pago",
    "Rechazar cita",
    "¿Está seguro que desea confirmar el pago y aceptar esta cita?",
    "¿Está seguro que desea rechazar esta cita?",
    "¿Está seguro que desea confirmar el pago y activar esta cita?",
    "Gestión de Facturas",
    "Menú",
    "Facturas",
    "Gestionar citas",
    "Total facturas",
    "Monto total",
    "Facturas pagadas",
    "Adelantos",
    "Buscar paciente, médico o número...",
    "Pagada",
    "Pendiente",
    "Vencida",
    "Reembolsada",
    "Desde",
    "Hasta",
    "Aplicar filtros",
    "Limpiar",
    "N° Factura",
    "Paciente",
    "Fecha consulta",
    "Estado",
    "Sin paciente",
    "Sin médico",
    "Adel.",
    "Emitida",
    "Borrador",
    "Anulada",
    "Atendida",
    "Pagada adelanto",
    "Ver detalle",
    "PDF",
    "No se encontraron facturas en el período seleccionado.",
    "Página",
    "de",
    "Anterior",
    "Siguiente",
    "Paciente:",
    "Médico:",
    "Fecha:",
    "Total:",
    "Monto no disponible",
    "Detalle de factura",
    "Clínica",
    "RIF:",
    "Dirección de la sede principal",
    "Concepto",
    "Cant.",
    "Precio",
    "Cargando conceptos...",
    "Descargar PDF",
    "Registrar pago",
    "Factura",
    "Monto a pagar",
    "Método de pago",
    "Referencia / N° operación",
    "Fecha de pago",
    "Efectivo",
    "Tarjeta",
    "Transferencia",
    "0.00",
    "Opcional",
    "Consulta médica",
    "Lista de Pacientes",
    "Pacientes registrados en el sistema",
    "Recepcionista",
    "Buscar por nombre, apellido, cédula o teléfono...",
    "Buscar",
    "Nombre",
    "Apellido",
    "Cédula",
    "Teléfono",
    "Menores a cargo",
    "No se encontraron pacientes con",
    "No hay pacientes registrados en el sistema.",
    "menores a cargo",
]

def add_or_update(po, msgid, msgstr):
    entry = po.find(msgid)
    if entry:
        entry.msgstr = msgstr
    else:
        entry = polib.POEntry(msgid=msgid, msgstr=msgstr)
        po.append(entry)

for lang, translations in [
    ('en', {s: s for s in strings}),
    ('pt', {
        "Panel de Recepción": "Painel de Recepção",
        "Dashboard": "Painel",
        "Citas": "Consultas",
        "Facturación": "Faturamento",
        "Pacientes": "Pacientes",
        "Cerrar sesión": "Sair",
        "Citas hoy": "Consultas hoje",
        "Programadas": "Agendadas",
        "Citas pendientes": "Consultas pendentes",
        "Por confirmar": "Para confirmar",
        "Pacientes nuevos hoy": "Novos pacientes hoje",
        "Registrados": "Registrados",
        "Médicos activos": "Médicos ativos",
        "En turno": "Em plantão",
        "Buscar paciente, médico o especialidad...": "Buscar paciente, médico ou especialidade...",
        "Registrar paciente": "Registrar paciente",
        "Gestión de Citas": "Gestão de Consultas",
        "Inicio": "Início",
        "Gestionar": "Gerenciar",
        "Administra todas las citas del sistema": "Gerencie todas as consultas do sistema",
        "Total citas": "Total de consultas",
        "Solicitudes": "Solicitações",
        "Pagos por confirmar": "Pagamentos para confirmar",
        "Aceptadas": "Aceitas",
        "Limpiar filtros": "Limpar filtros",
        "Todos los estados": "Todos os estados",
        "Solicitada": "Solicitada",
        "Aprobada": "Aprovada",
        "Pago Pendiente": "Pagamento Pendente",
        "Pagada (Adelanto)": "Paga (Adiantamento)",
        "Confirmada": "Confirmada",
        "En Consulta": "Em Consulta",
        "Atendida": "Atendida",
        "Cancelada": "Cancelada",
        "Rechazada": "Recusada",
        "No Asistió": "Não Compareceu",
        "Todas las citas": "Todas as consultas",
        "Solicitudes nuevas": "Novas solicitações",
        "citas en total": "consultas no total",
        "solicitudes pendientes": "solicitações pendentes",
        "en revisión": "em revisão",
        "aceptadas": "aceitas",
        "Sede": "Sede",
        "Médico": "Médico",
        "Acciones": "Ações",
        "Método Pago": "Método Pagamento",
        "Referencia": "Referência",
        "Monto": "Valor",
        "Fecha Cita": "Data Consulta",
        "Ver pago": "Ver pagamento",
        "Confirmar": "Confirmar",
        "Rechazar": "Recusar",
        "Confirmar Pago": "Confirmar Pagamento",
        "Cancelar": "Cancelar",
        "Sin acciones": "Sem ações",
        "No hay citas registradas.": "Nenhuma consulta registrada.",
        "No hay solicitudes nuevas.": "Nenhuma nova solicitação.",
        "No hay pagos pendientes de confirmación.": "Nenhum pagamento pendente de confirmação.",
        "Pago pendiente": "Pagamento pendente",
        "No asignado": "Não atribuído",
        "No registrado": "Não registrado",
        "Confirmar pago": "Confirmar pagamento",
        "Rechazar cita": "Recusar consulta",
        "¿Está seguro que desea confirmar el pago y aceptar esta cita?": "Tem certeza que deseja confirmar o pagamento e aceitar esta consulta?",
        "¿Está seguro que desea rechazar esta cita?": "Tem certeza que deseja recusar esta consulta?",
        "¿Está seguro que desea confirmar el pago y activar esta cita?": "Tem certeza que deseja confirmar o pagamento e ativar esta consulta?",
        "Gestión de Facturas": "Gestão de Faturas",
        "Menú": "Menu",
        "Facturas": "Faturas",
        "Gestionar citas": "Gerenciar consultas",
        "Total facturas": "Total de faturas",
        "Monto total": "Valor total",
        "Facturas pagadas": "Faturas pagas",
        "Adelantos": "Adiantamentos",
        "Buscar paciente, médico o número...": "Buscar paciente, médico ou número...",
        "Pagada": "Paga",
        "Pendiente": "Pendente",
        "Vencida": "Vencida",
        "Reembolsada": "Reembolsada",
        "Desde": "De",
        "Hasta": "Até",
        "Aplicar filtros": "Aplicar filtros",
        "Limpiar": "Limpar",
        "N° Factura": "N° Fatura",
        "Paciente": "Paciente",
        "Fecha consulta": "Data consulta",
        "Estado": "Estado",
        "Sin paciente": "Sem paciente",
        "Sin médico": "Sem médico",
        "Adel.": "Adiant.",
        "Emitida": "Emitida",
        "Borrador": "Rascunho",
        "Anulada": "Anulada",
        "Atendida": "Atendida",
        "Pagada adelanto": "Paga adiantamento",
        "Ver detalle": "Ver detalhes",
        "PDF": "PDF",
        "No se encontraron facturas en el período seleccionado.": "Nenhuma fatura encontrada no período selecionado.",
        "Página": "Página",
        "de": "de",
        "Anterior": "Anterior",
        "Siguiente": "Próxima",
        "Paciente:": "Paciente:",
        "Médico:": "Médico:",
        "Fecha:": "Data:",
        "Total:": "Total:",
        "Monto no disponible": "Valor não disponível",
        "Detalle de factura": "Detalhes da fatura",
        "Clínica": "Clínica",
        "RIF:": "RIF:",
        "Dirección de la sede principal": "Endereço da sede principal",
        "Concepto": "Conceito",
        "Cant.": "Qtd.",
        "Precio": "Preço",
        "Cargando conceptos...": "Carregando conceitos...",
        "Descargar PDF": "Baixar PDF",
        "Registrar pago": "Registrar pagamento",
        "Factura": "Fatura",
        "Monto a pagar": "Valor a pagar",
        "Método de pago": "Método de pagamento",
        "Referencia / N° operación": "Referência / N° operação",
        "Fecha de pago": "Data de pagamento",
        "Efectivo": "Dinheiro",
        "Tarjeta": "Cartão",
        "Transferencia": "Transferência",
        "0.00": "0,00",
        "Opcional": "Opcional",
        "Consulta médica": "Consulta médica",
        "Lista de Pacientes": "Lista de Pacientes",
        "Pacientes registrados en el sistema": "Pacientes registrados no sistema",
        "Recepcionista": "Recepcionista",
        "Buscar por nombre, apellido, cédula o teléfono...": "Buscar por nome, sobrenome, CPF ou telefone...",
        "Buscar": "Buscar",
        "Nombre": "Nome",
        "Apellido": "Sobrenome",
        "Cédula": "CPF",
        "Teléfono": "Telefone",
        "Menores a cargo": "Menores a cargo",
        "No se encontraron pacientes con": "Nenhum paciente encontrado com",
        "No hay pacientes registrados en el sistema.": "Não há pacientes registrados no sistema.",
        "menores a cargo": "menores a cargo",
    }),
]:
    po_path = os.path.join(BASE, 'locale', lang, 'LC_MESSAGES', 'django.po')
    mo_path = os.path.join(BASE, 'locale', lang, 'LC_MESSAGES', 'django.mo')
    po = polib.pofile(po_path)
    for s in strings:
        msgstr = translations.get(s, s)
        add_or_update(po, s, msgstr)
    po.save()
    po.save_as_mofile(mo_path)
    print(f'Updated {lang} .po and .mo')

print('All done!')
