# Generated by Django 6.0.4 on 2026-04-29 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL amigable para la sede', unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('paciente', 'Paciente'), ('paciente_especial', 'Paciente Especial'), ('medico', 'Médico'), ('recepcionista', 'Recepcionista'), ('gerente', 'Gerente'), ('gerente_general', 'Gerente General')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cedula', models.CharField(help_text='Cédula de identidad', max_length=15, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(blank=True, help_text='Sede asignada (no aplica para Gerente General)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.sede')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='PacienteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia_clinica_numero', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas')),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que toma actualmente')),
                ('condiciones_cronicas', models.TextField(blank=True, help_text='Condiciones crónicas')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=200)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=50)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.CharField(help_text='Matricula profesional', max_length=50, unique=True)),
                ('experiencia_anios', models.PositiveIntegerField(default=0)),
                ('biografia', models.TextField(blank=True)),
                ('consulta_precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.especialidad')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
            ],
        ),
    ]
