# Generated by Django 6.0.4 on 2026-05-06 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_historiaclinica_cita_remove_factura_cita_and_more'),
        ('usuarios', '0002_sync_inspectdb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicoprofile',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='medicoprofile',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='pacienteprofile',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sede',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('recepcionista', 'Recepcionista'), ('gerente', 'Gerente')], max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='MedicoProfile',
        ),
        migrations.DeleteModel(
            name='PacienteProfile',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
