# Generated by Django 6.0.4 on 2026-05-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_userprofile_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.TextField()),
                ('nombre_2', models.TextField(blank=True, null=True)),
                ('apellido_1', models.TextField()),
                ('apellido_2', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('tipo_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id_cm', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cm', models.TextField()),
                ('rif_cm', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'centro_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('capital', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionAdmin',
            fields=[
                ('id_direccion_admin', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('referencias', models.TextField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dirección de Administrador',
                'verbose_name_plural': 'Direcciones de Administradores',
                'db_table': 'direccion_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionDoctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dirección de Doctor',
                'verbose_name_plural': 'Direcciones de Doctores',
                'db_table': 'direccion_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionPaciente',
            fields=[
                ('id_direccion_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dirección de Paciente',
                'verbose_name_plural': 'Direcciones de Pacientes',
                'db_table': 'direccion_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionRecepcionista',
            fields=[
                ('id_direccion_recepcionista', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dirección de Recepcionista',
                'verbose_name_plural': 'Direcciones de Recepcionistas',
                'db_table': 'direccion_recepcionista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionSede',
            fields=[
                ('id_direccion_sede', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'direccion_sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionSuperadmin',
            fields=[
                ('id_direccion_superadmin', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'direccion_superadmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.TextField(blank=True, null=True)),
                ('nombre_2', models.TextField(blank=True, null=True)),
                ('apellido_1', models.TextField(blank=True, null=True)),
                ('apellido_2', models.TextField(blank=True, null=True)),
                ('id_especialidad_doctor', models.BigIntegerField(blank=True, null=True)),
                ('id_consultorio', models.BigIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('id_horario', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('iso_3166_2', models.CharField(blank=True, db_column='iso_3166-2', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacienteDatosPersonales',
            fields=[
                ('id_datos_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.TextField()),
                ('nombre_2', models.TextField(blank=True, null=True)),
                ('apellido_1', models.TextField()),
                ('apellido_2', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('tipo_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Datos Personales de Paciente',
                'verbose_name_plural': 'Datos Personales de Pacientes',
                'db_table': 'paciente_datos_personales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PacienteEspecial',
            fields=[
                ('id_paciente_especial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.TextField(blank=True, null=True)),
                ('nombre_2', models.TextField(blank=True, null=True)),
                ('apellido_1', models.TextField(blank=True, null=True)),
                ('apellido_2', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Paciente Especial',
                'verbose_name_plural': 'Pacientes Especiales',
                'db_table': 'paciente_especial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_parroquia', models.AutoField(primary_key=True, serialize=False)),
                ('parroquia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'parroquias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id_recepcionista', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.TextField()),
                ('nombre_2', models.TextField(blank=True, null=True)),
                ('apellido_1', models.TextField()),
                ('apellido_2', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('tipo_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('id_horario', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recepcionista',
                'verbose_name_plural': 'Recepcionistas',
                'db_table': 'recepcionista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasenaAdmin',
            fields=[
                ('id_recuperacion_contrasena_admin', models.BigAutoField(primary_key=True, serialize=False)),
                ('preguntas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
                ('respuestas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'recuperacion_contrasena_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasenaDoctor',
            fields=[
                ('id_recuperacion_contrasena_doctor', models.BigAutoField(primary_key=True, serialize=False)),
                ('preguntas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
                ('respuestas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'recuperacion_contrasena_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasenaPaciente',
            fields=[
                ('id_recuperar_contrasena_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('preguntas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
                ('respuestas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'recuperacion_contrasena_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasenaRecepcionista',
            fields=[
                ('id_recuperacion_recepcionista', models.BigAutoField(primary_key=True, serialize=False)),
                ('preguntas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
                ('respuestas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'recuperacion_contrasena_recepcionista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecuperacionContrasenaSuperadmin',
            fields=[
                ('id_recuperacion_contrasena_superadmin', models.BigAutoField(primary_key=True, serialize=False)),
                ('preguntas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
                ('respuestas_seguridad', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'recuperacion_contrasena_superadmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id_root', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Root',
                'verbose_name_plural': 'Roots',
                'db_table': 'root',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.BigAutoField(primary_key=True, serialize=False)),
                ('rif_sede', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('nombre_sede', models.TextField()),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Superadmin',
            fields=[
                ('id_superadmin', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_1', models.TextField(blank=True, null=True)),
                ('nombre_2', models.TextField(blank=True, null=True)),
                ('apellido_1', models.TextField(blank=True, null=True)),
                ('apellido_2', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Superadmin',
                'verbose_name_plural': 'Superadmins',
                'db_table': 'superadmin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id_user_admin', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('email', models.EmailField(db_column='correo', max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'verbose_name': 'Usuario Administrador',
                'verbose_name_plural': 'Usuarios Administradores',
                'db_table': 'user_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDoctor',
            fields=[
                ('id_user_doctor', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('email', models.EmailField(db_column='correo', max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'verbose_name': 'Usuario Doctor',
                'verbose_name_plural': 'Usuarios Doctores',
                'db_table': 'user_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPaciente',
            fields=[
                ('id_user_paciente', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('email', models.EmailField(db_column='correo', max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'verbose_name': 'Usuario Paciente',
                'verbose_name_plural': 'Usuarios Pacientes',
                'db_table': 'user_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRecepcionista',
            fields=[
                ('id_user_recepcionista', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='contrasena', max_length=255)),
                ('email', models.EmailField(db_column='correo', max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'verbose_name': 'Usuario Recepcionista',
                'verbose_name_plural': 'Usuarios Recepcionistas',
                'db_table': 'user_recepcionista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoot',
            fields=[
                ('id_user_root', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasena', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario Root',
                'verbose_name_plural': 'Usuarios Root',
                'db_table': 'user_root',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSuperAdmin',
            fields=[
                ('id_superadmin', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('contrasena', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario SuperAdmin',
                'verbose_name_plural': 'Usuarios SuperAdmin',
                'db_table': 'user_superadmin',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False, 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
    ]
