# Generated by Django 6.0.4 on 2026-04-29 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=20)),
                ('notas_paciente', models.TextField(blank=True, help_text='Notas del paciente para la cita')),
                ('notas_medico', models.TextField(blank=True, help_text='Notas del médico después de la cita')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to='usuarios.medicoprofile')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.sede')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, help_text='Método de pago utilizado', max_length=50)),
                ('referencia_pago', models.CharField(blank=True, help_text='Referencia de pago', max_length=100)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='citas.cita')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField(help_text='Motivo principal de la consulta')),
                ('sintomas', models.TextField(help_text='Síntomas descritos por el paciente')),
                ('diagnostico', models.TextField(help_text='Diagnóstico del médico')),
                ('tratamiento', models.TextField(blank=True, help_text='Plan de tratamiento')),
                ('medicamentos_recetados', models.TextField(blank=True, help_text='Medicamentos recetados')),
                ('dosis_medicamentos', models.TextField(blank=True, help_text='Dosis y frecuencia')),
                ('estudios_solicitados', models.TextField(blank=True, help_text='Estudios de laboratorio o imagenología')),
                ('dias_reposo', models.PositiveIntegerField(default=0, help_text='Días de reposo recomendados')),
                ('indicaciones_reposo', models.TextField(blank=True, help_text='Indicaciones específicas del reposo')),
                ('ordenes_medicas', models.TextField(blank=True, help_text='Órdenes médicas especiales')),
                ('proxima_cita_sugerida', models.DateField(blank=True, help_text='Fecha sugerida para próxima consulta', null=True)),
                ('firma_medico', models.BooleanField(default=False, help_text='Firma digital del médico')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='citas.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medicoprofile')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='usuarios.pacienteprofile')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('citas_diarias', 'Citas Diarias'), ('citas_semanales', 'Citas Semanales'), ('citas_mensuales', 'Citas Mensuales'), ('facturacion_mensual', 'Facturación Mensual'), ('pacientes_nuevos', 'Pacientes Nuevos'), ('medicos_activos', 'Médicos Activos'), ('rendimiento_sede', 'Rendimiento por Sede')], max_length=30)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del período')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('datos_json', models.JSONField(default=dict, help_text='Datos del reporte en formato JSON')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.sede')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duración en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.especialidad')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.servicio'),
        ),
        migrations.CreateModel(
            name='DisponibilidadMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medicoprofile')),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
