# Generated by Django 6.0.5 on 2026-05-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
    ]
