# Generated by Django 6.0.4 on 2026-05-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_sync_inspectdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cita',
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadmedica',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='disponibilidadmedica',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='generado_por',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='especialidad',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='DisponibilidadMedica',
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
