# Generated by Django 6.0.4 on 2026-05-28 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_especialidad_alter_cita_sede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id_alergias', models.BigAutoField(primary_key=True, serialize=False)),
                ('alergias', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'alergias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_consultorio', models.BigAutoField(primary_key=True, serialize=False)),
                ('consultorios', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'db_table': 'consultorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id_enfermedades', models.BigAutoField(primary_key=True, serialize=False)),
                ('enfermedades', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enfermedades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecialidadDoctor',
            fields=[
                ('id_especialidad_doctor', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especialidad_doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialAlergias',
            fields=[
                ('id_historial_alergias', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'historial_alergias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialEnfermedades',
            fields=[
                ('id_historial_enfermedades', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'historial_enfermedades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialMedicoPaciente',
            fields=[
                ('id_historial_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'historial_medico_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaVacunas',
            fields=[
                ('id_historial_vacunas', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'historia_vacunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoCita',
            fields=[
                ('id_pagos_cita', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_consulta', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('id_cita', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pago de Cita',
                'verbose_name_plural': 'Pagos de Citas',
                'db_table': 'pagos_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreciosServicios',
            fields=[
                ('id_precios_servicios', models.BigAutoField(primary_key=True, serialize=False)),
                ('precios', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'precios_servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id_recipes', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recipes',
                'ordering': ['-fecha_emision'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeDiagnostico',
            fields=[
                ('id_recipe_diagnostico', models.BigAutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'recipe_diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeEstudios',
            fields=[
                ('id_recipe_estudios', models.BigAutoField(primary_key=True, serialize=False)),
                ('estudios_realizar', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'recipe_estudios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeMedicamentosEspeciales',
            fields=[
                ('id_recipe_medicamento_especiales', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicamentos_especiales', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'recipe_medicamentos_especiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeReposo',
            fields=[
                ('id_recipe_reposo', models.BigAutoField(primary_key=True, serialize=False)),
                ('reposo', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'recipe_reposo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipesOrdenesMedicas',
            fields=[
                ('id_recipe_ordenes', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordenes_medicas', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'recipes_ordenes_medicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeTratamiento',
            fields=[
                ('id_recipe_tratamiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tratamiento_necesario', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'recipe_tratamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioEspecialidad',
            fields=[
                ('id_servicios_especialidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('servicios', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio Especialidad',
                'verbose_name_plural': 'Servicios Especialidad',
                'db_table': 'servicios_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id_tipo_sangre', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tipo_sangre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id_vacunas', models.BigAutoField(primary_key=True, serialize=False)),
                ('vacunas_cumplidas', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vacunas',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='especialidad',
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'managed': False, 'ordering': ['-fecha_consulta'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'managed': False, 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id_consulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.TextField()),
                ('enfermedad_actual', models.TextField(blank=True, null=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('plan_tratamiento', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], default='abierta', max_length=20)),
                ('id_cita', models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.PROTECT, related_name='consulta_medica', to='citas.cita')),
            ],
            options={
                'db_table': 'consultas_medicas',
            },
        ),
        migrations.DeleteModel(
            name='HorarioMedico',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
