# Generated by Django 6.0.4 on 2026-05-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_consulta_medica'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cita',
            table='citas',
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table='especialidades',
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='emitida', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('id_cita', models.OneToOneField(db_column='id_cita', on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='citas.cita')),
                ('id_pago_cita', models.ForeignKey(db_column='id_pago_cita', on_delete=django.db.models.deletion.PROTECT, to='citas.pagocita')),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
    ]
