# Generated by Django 6.0.4 on 2026-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultamedica',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': False},
        ),
    ]
